import { Server } from '@/types';

// Mock servers to display when database is empty
export const mockServers: Server[] = [
  {
    id: 'mock-1',
    name: 'Hynetic',
    description: 'Server ONLINE! Hynetic is a modern Hytale minigame server featuring unique game modes, custom maps, and an active community. Join us for endless fun!',
    short_description: 'Modern Hytale minigame server with unique modes',
    ip_address: 'play.hynetic.com',
    port: 25565,
    website_url: 'https://hynetic.com',
    discord_url: 'https://discord.gg/hynetic',
    banner_image_url: null,
    game_modes: ['pvp', 'mini-games', 'pve'],
    tags: ['minigames', 'competitive', 'events'],
    version: '1.0.0',
    region: 'north-america',
    max_players: 500,
    current_players: 127,
    screenshots: [],
    is_online: true,
    is_featured: true,
    votes: 418,
    views: 12500,
    status: 'approved',
    owner_id: 'mock-owner-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    name: 'Hytale Box',
    description: 'Hytale Box es un servidor hispano totalmente dedicado a la comunidad hispanohablante. Ofrecemos survival, PvP y mucho más!',
    short_description: 'Servidor hispano con survival y PvP',
    ip_address: 'play.hytalebox.com',
    port: 25565,
    website_url: 'https://hytalebox.com',
    discord_url: 'https://discord.gg/hytalebox',
    banner_image_url: null,
    game_modes: ['roleplay', 'pvp', 'survival', 'pve'],
    tags: ['spanish', 'community', 'survival'],
    version: '1.0.0',
    region: 'south-america',
    max_players: 200,
    current_players: null,
    screenshots: [],
    is_online: false,
    is_featured: false,
    votes: 261,
    views: 8900,
    status: 'approved',
    owner_id: 'mock-owner-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    name: '2b2t Hytale',
    description: "We've recreated the same Minecraft 2b2t server in Hytale. We're pleased to announce the oldest anarchy server is now available!",
    short_description: 'The oldest anarchy server, now in Hytale',
    ip_address: '2b2t.hytale.org',
    port: 25565,
    website_url: null,
    discord_url: 'https://discord.gg/2b2thytale',
    banner_image_url: null,
    game_modes: ['pvp', 'survival', 'vanilla'],
    tags: ['anarchy', 'no-rules', 'hardcore'],
    version: '1.0.0',
    region: 'north-america',
    max_players: 1000,
    current_players: 342,
    screenshots: [],
    is_online: true,
    is_featured: false,
    votes: 212,
    views: 15600,
    status: 'approved',
    owner_id: 'mock-owner-3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    name: 'AnarchyHQ',
    description: 'ANARCHY HQ - Hytales Most Hostile Server! No rules, no admins, pure chaos. Survive if you can in this lawless world.',
    short_description: 'No rules anarchy server - pure chaos',
    ip_address: 'anarchyhq.com',
    port: 25565,
    website_url: 'https://anarchyhq.com',
    discord_url: null,
    banner_image_url: null,
    game_modes: ['pvp', 'survival', 'vanilla'],
    tags: ['anarchy', 'chaos', 'no-rules'],
    version: '1.0.0',
    region: 'europe',
    max_players: 500,
    current_players: 89,
    screenshots: [],
    is_online: true,
    is_featured: false,
    votes: 156,
    views: 7200,
    status: 'approved',
    owner_id: 'mock-owner-4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    name: 'Hyzen',
    description: 'Servidor Survival RPG de Hytale con enfoque en estabilidad, progresión y comunidad. Características únicas y eventos semanales.',
    short_description: 'Survival RPG with progression system',
    ip_address: 'play.hyzen.net',
    port: 25565,
    website_url: 'https://hyzen.net',
    discord_url: 'https://discord.gg/hyzen',
    banner_image_url: null,
    game_modes: ['survival', 'rpg', 'pve'],
    tags: ['rpg', 'progression', 'events'],
    version: '1.0.0',
    region: 'europe',
    max_players: 300,
    current_players: 67,
    screenshots: [],
    is_online: true,
    is_featured: true,
    votes: 143,
    views: 5400,
    status: 'approved',
    owner_id: 'mock-owner-5',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    name: 'Hyvexa',
    description: "World's first Parkour Server on Hytale. Jump into the action with hundreds of unique parkour maps and challenges!",
    short_description: 'First dedicated parkour server',
    ip_address: 'hyvexa.net',
    port: 25565,
    website_url: 'https://hyvexa.net',
    discord_url: 'https://discord.gg/hyvexa',
    banner_image_url: null,
    game_modes: ['mini-games', 'adventure'],
    tags: ['parkour', 'challenges', 'maps'],
    version: '1.0.0',
    region: 'north-america',
    max_players: 250,
    current_players: 45,
    screenshots: [],
    is_online: true,
    is_featured: false,
    votes: 130,
    views: 4100,
    status: 'approved',
    owner_id: 'mock-owner-6',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-7',
    name: 'CraftHytale',
    description: 'Classic survival experience with modern features. Land claims, economy, and friendly community. Perfect for beginners!',
    short_description: 'Classic survival with land claims',
    ip_address: 'crafthytale.com',
    port: 25565,
    website_url: 'https://crafthytale.com',
    discord_url: 'https://discord.gg/crafthytale',
    banner_image_url: null,
    game_modes: ['survival', 'pve', 'vanilla'],
    tags: ['beginner-friendly', 'economy', 'claims'],
    version: '1.0.0',
    region: 'europe',
    max_players: 150,
    current_players: 34,
    screenshots: [],
    is_online: true,
    is_featured: false,
    votes: 98,
    views: 3200,
    status: 'approved',
    owner_id: 'mock-owner-7',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-8',
    name: 'SkyRealms',
    description: 'Ultimate Skyblock experience in Hytale! Custom islands, challenges, and competitive leaderboards. Build your empire in the sky!',
    short_description: 'Ultimate skyblock experience',
    ip_address: 'skyrealms.gg',
    port: 25565,
    website_url: 'https://skyrealms.gg',
    discord_url: 'https://discord.gg/skyrealms',
    banner_image_url: null,
    game_modes: ['skyblock', 'survival'],
    tags: ['skyblock', 'competitive', 'islands'],
    version: '1.0.0',
    region: 'asia',
    max_players: 400,
    current_players: 156,
    screenshots: [],
    is_online: true,
    is_featured: false,
    votes: 187,
    views: 6800,
    status: 'approved',
    owner_id: 'mock-owner-8',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-9',
    name: 'HytalePVP',
    description: 'Competitive PvP server with ranked matches, tournaments, and custom game modes. Prove your skills against the best!',
    short_description: 'Competitive PvP with ranked matches',
    ip_address: 'hytalepvp.net',
    port: 25565,
    website_url: 'https://hytalepvp.net',
    discord_url: 'https://discord.gg/hytalepvp',
    banner_image_url: null,
    game_modes: ['pvp', 'mini-games'],
    tags: ['pvp', 'ranked', 'tournaments'],
    version: '1.0.0',
    region: 'north-america',
    max_players: 600,
    current_players: 234,
    screenshots: [],
    is_online: true,
    is_featured: true,
    votes: 312,
    views: 11200,
    status: 'approved',
    owner_id: 'mock-owner-9',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
